/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moonbucks;
import java.awt.Component;
import javax.swing.JTextField;
import javax.swing.UnsupportedLookAndFeelException;
import java.text.SimpleDateFormat;
import java.util.Calendar;


/**
 *
 * @author User
 */
public class moonbucks extends javax.swing.JFrame {
  

    /**
     * Creates new form moonbucks
     */
    public moonbucks() {
        initComponents();
        
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlblBCGM = new javax.swing.JLabel();
        jlblPB = new javax.swing.JLabel();
        jlblBCM = new javax.swing.JLabel();
        jtxtBCM = new javax.swing.JTextField();
        jtxtPB = new javax.swing.JTextField();
        jtxtBCGM = new javax.swing.JTextField();
        jlblFood = new javax.swing.JLabel();
        jlblMMM = new javax.swing.JLabel();
        jlblSCP = new javax.swing.JLabel();
        jlblCBD = new javax.swing.JLabel();
        jtxtMMM = new javax.swing.JTextField();
        jtxtSCP = new javax.swing.JTextField();
        jtxtCBD = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jlblICL = new javax.swing.JLabel();
        jlblICM = new javax.swing.JLabel();
        jlblCM = new javax.swing.JLabel();
        jtxtCM = new javax.swing.JTextField();
        jtxtICM = new javax.swing.JTextField();
        jtxtICL = new javax.swing.JTextField();
        jlblICA = new javax.swing.JLabel();
        jlblCA = new javax.swing.JLabel();
        jlblEM = new javax.swing.JLabel();
        jtxtICA = new javax.swing.JTextField();
        jtxtCA = new javax.swing.JTextField();
        jtxtEM = new javax.swing.JTextField();
        jlblDrink = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jbtnTotal = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jlblCOD = new javax.swing.JLabel();
        jlblCOF = new javax.swing.JLabel();
        jlblTDF = new javax.swing.JLabel();
        jtxtTDF = new javax.swing.JTextField();
        jtxtCOF = new javax.swing.JTextField();
        jtxtCOD = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jlblTax = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jlblMOONBUCKS = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 102));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5));
        jPanel1.setForeground(new java.awt.Color(255, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 6));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblBCGM.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblBCGM.setText("Asam Laksa Nyonya (RM 5)");
        jPanel2.add(jlblBCGM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jlblPB.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblPB.setText("Nasi Lemak (RM 5)");
        jPanel2.add(jlblPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jlblBCM.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblBCM.setText("Nasi Dagang (RM 5)");
        jPanel2.add(jlblBCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jtxtBCM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBCM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBCM.setText("0");
        jPanel2.add(jtxtBCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 40, 35));

        jtxtPB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtPB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPB.setText("0");
        jPanel2.add(jtxtPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 40, 35));

        jtxtBCGM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtBCGM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBCGM.setText("0");
        jPanel2.add(jtxtBCGM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 40, 35));

        jlblFood.setFont(new java.awt.Font("Death Star", 0, 48)); // NOI18N
        jlblFood.setForeground(new java.awt.Color(0, 153, 153));
        jlblFood.setText("FOOD");
        jPanel2.add(jlblFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jlblMMM.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblMMM.setText("Spaghetti Bolognese (RM 12)");
        jPanel2.add(jlblMMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jlblSCP.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblSCP.setText("Spaghetti Aglio Olio (RM 12)");
        jPanel2.add(jlblSCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jlblCBD.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblCBD.setText("Lamb Chop (RM 16)");
        jPanel2.add(jlblCBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jtxtMMM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtMMM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMMM.setText("0");
        jPanel2.add(jtxtMMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 40, 35));

        jtxtSCP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtSCP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSCP.setText("0");
        jPanel2.add(jtxtSCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 40, 35));

        jtxtCBD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCBD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCBD.setText("0");
        jPanel2.add(jtxtCBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 40, 35));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 584, 430));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 6));
        jPanel3.setForeground(new java.awt.Color(0, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblICL.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblICL.setText("Strawberry Milkshake (RM 6)");
        jPanel3.add(jlblICL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jlblICM.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblICM.setText("Coconut Milkshake (RM 6)");
        jPanel3.add(jlblICM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jlblCM.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblCM.setText("Orange Juice (RM 3)");
        jPanel3.add(jlblCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jtxtCM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCM.setText("0");
        jtxtCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCMActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtCM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 40, 35));

        jtxtICM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtICM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtICM.setText("0");
        jtxtICM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtICMActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtICM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 40, 35));

        jtxtICL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtICL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtICL.setText("0");
        jPanel3.add(jtxtICL, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 40, 35));

        jlblICA.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblICA.setText("Green Tea Milkshake (RM 6)");
        jPanel3.add(jlblICA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jlblCA.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblCA.setText("Mango Juice (RM 6)");
        jPanel3.add(jlblCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 30));

        jlblEM.setFont(new java.awt.Font("Tw Cen MT", 0, 21)); // NOI18N
        jlblEM.setText("Watermelon Juice (RM 6)");
        jPanel3.add(jlblEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jtxtICA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtICA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtICA.setText("0");
        jPanel3.add(jtxtICA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 40, 35));

        jtxtCA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtCA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtCA.setText("0");
        jPanel3.add(jtxtCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 40, 35));

        jtxtEM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtEM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtEM.setText("0");
        jtxtEM.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel3.add(jtxtEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 40, 35));

        jlblDrink.setFont(new java.awt.Font("Death Star", 0, 48)); // NOI18N
        jlblDrink.setForeground(new java.awt.Color(0, 153, 153));
        jlblDrink.setText("DRINKS");
        jPanel3.add(jlblDrink, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("A little sunshine", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 153));
        jLabel1.setText("SHAKES");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 30));

        jLabel2.setFont(new java.awt.Font("A little sunshine", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 153));
        jLabel2.setText("JUICE");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 434, 430));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 310, 570));

        jbtnTotal.setBackground(new java.awt.Color(255, 102, 102));
        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnTotal.setText("TOTAL");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 100, 30));

        jbtnReceipt.setBackground(new java.awt.Color(255, 102, 102));
        jbtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnReceipt.setText("RECEIPT");
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 100, 30));

        jbtnReset.setBackground(new java.awt.Color(255, 102, 102));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnReset.setText("RESET");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 90, 30));

        jbtnExit.setBackground(new java.awt.Color(255, 102, 102));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnExit.setText("EXIT");
        jbtnExit.setToolTipText("");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 90, 30));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 6));
        jPanel6.setForeground(new java.awt.Color(0, 102, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblCOD.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblCOD.setForeground(new java.awt.Color(255, 255, 255));
        jlblCOD.setText("COST OF DRINKS");
        jPanel6.add(jlblCOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jlblCOF.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblCOF.setForeground(new java.awt.Color(255, 255, 255));
        jlblCOF.setText("COST OF FOOD");
        jPanel6.add(jlblCOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jlblTDF.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblTDF.setForeground(new java.awt.Color(255, 255, 255));
        jlblTDF.setText("TOTAL D & F");
        jPanel6.add(jlblTDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jtxtTDF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtTDF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(jtxtTDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 110, 30));

        jtxtCOF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtCOF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(jtxtCOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 110, 30));

        jtxtCOD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtCOD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(jtxtCOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 110, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 290, 130));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 6));
        jPanel5.setForeground(new java.awt.Color(0, 102, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblTax.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblTax.setForeground(new java.awt.Color(255, 255, 255));
        jlblTax.setText("TAX (6%)");
        jPanel5.add(jlblTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jlblTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlblTotal.setText("TOTAL");
        jPanel5.add(jlblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jlblSubTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlblSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        jlblSubTotal.setText("SUBTOTAL");
        jPanel5.add(jlblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 110, 30));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 110, 30));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 110, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 290, 130));

        jlblMOONBUCKS.setFont(new java.awt.Font("Death Star", 0, 72)); // NOI18N
        jlblMOONBUCKS.setForeground(new java.awt.Color(255, 102, 0));
        jlblMOONBUCKS.setText("MAKAN-MAKAN");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moonbucks/ANA.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel3)
                .addGap(83, 83, 83)
                .addComponent(jlblMOONBUCKS, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jlblMOONBUCKS))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
       SubClass ItemCost = new SubClass ();
       
       double iTax,iSubTotal,iTotal ;
       double taxrate=0.06;
       
       ItemCost.OrangeJuice = ItemCost.pOrangeJuice * Double.parseDouble(jtxtCM.getText());
       ItemCost.MangoJuice = ItemCost.pMangoJuice * Double.parseDouble(jtxtICM.getText());
       ItemCost.WatermelonJuice = ItemCost.pWatermelonJuice * Double.parseDouble(jtxtICL.getText());
       ItemCost.CoconutMilkshake = ItemCost.pCoconutMilkshake * Double.parseDouble(jtxtCA.getText());
       ItemCost.StrawberryMilkshake = ItemCost.pStrawberryMilkshake * Double.parseDouble(jtxtICA.getText());
       ItemCost.GreenTeaMilkShake = ItemCost.pGreenTeaMilkShake * Double.parseDouble(jtxtEM.getText());
       
       ItemCost.NasiDagang = ItemCost.pNasiDagang * Double.parseDouble(jtxtBCM.getText());
       ItemCost.NasiLemak = ItemCost.pNasiLemak * Double.parseDouble(jtxtPB.getText());
       ItemCost.AsamLaksaNyonya = ItemCost.pAsamLaksaNyonya * Double.parseDouble(jtxtBCGM.getText());
       ItemCost.SpaghettiBolognese = ItemCost.pSpaghettiBolognese * Double.parseDouble(jtxtMMM.getText());
       ItemCost.SpaghettiAglioOlio = ItemCost.pSpaghettiAglioOlio * Double.parseDouble(jtxtSCP.getText());
       ItemCost.LambChop = ItemCost.pLambChop * Double.parseDouble(jtxtCBD.getText());
    
    //===============CalculationForTax/SubTotal/Total====================================
       iSubTotal = ItemCost.GetAmount();
       iTax = iSubTotal * taxrate; 
       iTotal = iSubTotal + iTax;
      
       
       String SubTotal= String.format("RM %.2f", iSubTotal);
       jtxtSubTotal.setText(SubTotal);
       
       String Tax= String.format("RM %.2f", iTax);
       jtxtTax.setText(Tax);
       
       String Total= String.format("RM %.2f", iTotal);
       jtxtTotal.setText(Total);
       
    //==================CalculationForDrink/Food=====================================   
       String Drink= String.format("RM %.2f", ItemCost.Drink);
       jtxtCOD.setText(Drink);
       
       String Food= String.format("RM %.2f", ItemCost.Food);
       jtxtCOF.setText(Food);
       
       String TotalCostDF= String.format("RM %.2f", ItemCost.TotalDF);
       jtxtTDF.setText(TotalCostDF);
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        SubClass iExit = new SubClass();
        
        iExit.iExitSystem();
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        JTextField cleartext = null;
        
        for(Component c:jPanel3.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
     //===============================================================
        
        for(Component c:jPanel2.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
     //===============================================================
            for(Component c:jPanel5.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
     //===============================================================
        
        for(Component c:jPanel6.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        
      //==============================================================
        jtxtReceipt.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed
      
     //==================CreateRandomNumForRef=====================
       // int refs=1 + (int) (Math.random()*111);
        
     //========================================================
        Calendar timer= Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-yyyy");
        Tdate.format(timer.getTime());
        
        
       jtxtReceipt.append("\n                    Makan - Makan\n" + 
                          " \n              LOCAL MEETS WESTERN  \n "
                              +
    //                      "\nReference:\t\t" + refs +
           "\n===========================\n" + 
               "Drink:\t\t"+ jtxtCOD.getText()+ "\n\n" +
               "Food:\t\t"+ jtxtCOF.getText()+ "\n\n" +
               "Cost Of Item:\t\t"+ jtxtTDF.getText()+ "\n" +
               
           "\n===========================\n" +
               
               "Tax (6%):\t\t"+ jtxtTax.getText()+ "\n\n" +
               "SubTotal:\t\t"+ jtxtSubTotal.getText()+ "\n\n" +
               "Total:\t\t"+ jtxtTotal.getText()+ "\n" +
               
           "\n===========================\n\n" +
               
               "                   Date: "+Tdate.format(timer.getTime())+
               "\n                     Time: "+tTime.format(timer.getTime())+
               
               "\n\tThank You\n" );
                       
 
     
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    private void jtxtCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCMActionPerformed

    private void jtxtICMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtICMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtICMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, IllegalAccessException, InstantiationException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(moonbucks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(moonbucks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(moonbucks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(moonbucks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new moonbucks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JLabel jlblBCGM;
    private javax.swing.JLabel jlblBCM;
    private javax.swing.JLabel jlblCA;
    private javax.swing.JLabel jlblCBD;
    private javax.swing.JLabel jlblCM;
    private javax.swing.JLabel jlblCOD;
    private javax.swing.JLabel jlblCOF;
    private javax.swing.JLabel jlblDrink;
    private javax.swing.JLabel jlblEM;
    private javax.swing.JLabel jlblFood;
    private javax.swing.JLabel jlblICA;
    private javax.swing.JLabel jlblICL;
    private javax.swing.JLabel jlblICM;
    private javax.swing.JLabel jlblMMM;
    private javax.swing.JLabel jlblMOONBUCKS;
    private javax.swing.JLabel jlblPB;
    private javax.swing.JLabel jlblSCP;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblTDF;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JTextField jtxtBCGM;
    private javax.swing.JTextField jtxtBCM;
    private javax.swing.JTextField jtxtCA;
    private javax.swing.JTextField jtxtCBD;
    private javax.swing.JTextField jtxtCM;
    private javax.swing.JTextField jtxtCOD;
    private javax.swing.JTextField jtxtCOF;
    private javax.swing.JTextField jtxtEM;
    private javax.swing.JTextField jtxtICA;
    private javax.swing.JTextField jtxtICL;
    private javax.swing.JTextField jtxtICM;
    private javax.swing.JTextField jtxtMMM;
    private javax.swing.JTextField jtxtPB;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtSCP;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTDF;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables

    
}
